apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app-name: grafana
spec:
  hostname: grafana
  containers:
  - name:  grafana
    #image: 192.168.1.31:5000/grafana:latest
    image: grafana/grafana:latest
    env:
    - name: TZ
      value: Japan
    volumeMounts:
    - name: grafana-lib
      mountPath: /var/lib/grafana
    - name: grafana-log
      mountPath: /var/log/grafana
    - name: localtime
      mountPath: /etc/localtime
    ports:
    - containerPort: 3000
      protocol: TCP
  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
  - name: grafana-lib
    hostPath:
      path: /opt/kubernetes/volumes/docker/grafana/lib
  - name: grafana-log
    hostPath:
      path: /opt/kubernetes/volumes/docker/grafana/log
---
apiVersion: v1
kind:       Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app-name: grafana
  ports:
  - protocol:   TCP
    name:       app
    port:       3000
    nodePort:   3000
    targetPort: 3000
