apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
  app-name: docker-registry
spec:
  hostname: private-registry
  containers:
  - name: registry
  image: registry:2.6
  volumeMounts:
  - name: registry-volume
  mountPath: /var/lib/registry
  ports:
  - containerPort: 5000
  protocol: TCP
  - name: registry-web
  image: hyper/docker-registry-web:v0.1.2
  env:
  - name: REGISTRY_NAME
  value: private-registry
  ports:
  - containerPort: 8080
  protocol: TCP
  volumes:
  - name: registry-volume
  hostPath:
    path: /opt/kube/volumes/docker/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
  app-name: docker-registry
  ports:
  - protocol: TCP
  name: app
  port: 5000
  nodePort: 5000
  targetPort: 5000
  - protocol: TCP
  name: web
  port: 8080
  nodePort: 8080
  targetPort: 8080